### ISSUE TITLE
\unless has no effect in \unravel with TL 19

### ISSUE THREAD

**Issue by PhelypeOleinik** [blefloch/latex-unravel#32]
The following code:

```latex
\documentclass{article}
\usepackage{unravel}

\ExplSyntaxOn
\prg_new_conditional:Npnn \pho_if_minus:n #1 { TF }
  {
    \reverse_if:N \if_charcode:w #1 - \exp_not:N \ERROR
      \prg_return_false:
    \else:
      \prg_return_true:
    \fi:
  }
\cs_new:Npn \test #1 { #1|-> \pho_if_minus:nTF {#1} { T } { F } \par }
\ExplSyntaxOff

\begin{document}

\ttfamily

\test{+}
\test{-}

\unravel{\test{+}}
\unravel{\test{-}}

\end{document}
```

Produces different output for `\test{-}` and `\test{+}` if they were used inside `\unravel`:

```none
+|->F
-|->T
+|->T
-|->F
```

With TeXLive 2018 the output is the same:

```none
+|->F
-|->T
+|->F
-|->T
```

**Comment by blefloch** [comment]
Thanks for the report!  For the record, a shorter test file, and partial
analysis that I'll come back to, later:

\RequirePackage{unravel}
\unravel{\unless\if--\BOOM\fi}
\stop

On the other hand, \unless\ifnum works as expected.  The issue seems to
be that \__unravel_unless: stores \reverse_if:N into
\l__unravel_head_tl, which is used only for some of the conditionals.
E.g., the second set of conditionals listed in \__unravel_cond_aux:n are
likely ok, but the first set are not.

Ah, \__unravel_test_two_chars:nn, used for \if and \ifcat calls

  \__unravel_prev_input_gpush_gtl:N \l__unravel_head_gtl

instead of the tl version.  There was certainly a reason for that, even
though I forget it.  One way out would probably be to change
\__unravel_unless: to make it set \l__unravel_head_gtl and not just the
corresponding tl, but I have to look more carefully.

**Comment by PhelypeOleinik** [comment]
I didn't put too much effort in minimising the code, sorry.

I tried changing

```latex
\tl_put_left:Nn \l__unravel_head_tl { \reverse_if:N }
```

into

```latex
\gtl_put_left:Nn \l__unravel_head_gtl { \reverse_if:N }
```

as you suggested and got a ``You can't use `\unless' before `\noexpand'.``

Looking at `\__unravel_test_two_chars:nn` I discovered that the `\l__unravel_head_tl` at the end contained `\reverse_if:N \exp_not:N \if \exp_not:N -`, thus raising the error above. That stray `\exp_not:N` is added by `\__unravel_test_two_chars_gtl:N`. However removing the `\exp_not:N` from there makes `\l__unravel_head_tl` contain only `\reverse_if:N \if -`, which doesn't error but I think is not good either. Plus, there is a `-` missing from `\l__unravel_head_tl` so the test won't work. My brain didn't let me go any further. I couldn't unravel `\unravel` :(

**Comment by PhelypeOleinik** [comment]
Hm... Another issue that comes from this same part of the code is:

```latex
\RequirePackage{unravel}
\unravel{\if##\fi}
\stop
```

which also worked in TL 2018.

I tracked the issue down to the `\tl_put_right:Nx` in `\__unravel_test_two_chars_gtl:N`, which tries to expand the `#` after `\gtl_head_do:NN` does its thing. Since `\gtl_head_do:NN` is `f`-expandable I changed (in the definition of `\__unravel_test_two_chars_gtl:N`):
```latex
              { \exp_not:N \exp_not:N \gtl_head_do:NN #1 \exp_not:N }
```
to
```latex
              {
                \exp_not:N \exp_not:N
                \exp_not:f { \gtl_head_do:NN #1 \exp_not:N }
              }
```
and it seems to be working again :-)

If you'd like I can open a new issue for this.

**Comment by blefloch** [comment]
I had fixed the second issue with a variant of your fix, and now the first issue is fixed as well.
